name: Test Failure Workflow

"on":
  workflow_dispatch:
  push:
    branches:
      - main # Or whatever your main branch is called
    

jobs:
  fail-job:
    runs-on: ubuntu-latest
    steps:
      - name: Always Fail Step
        run: |
          echo "This workflow is designed to fail."
          exit 1
